using System.Security;
using System.Runtime.CompilerServices;
using System.ComponentModel;
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Runtime.InteropServices;

namespace NativeLibrary
{
using System.Net.Http;
    using System.Threading;
    using Soulseek;
    public static class Program
    {
        private static SoulseekClient client;

        [UnmanagedCallersOnly(EntryPoint = "start_up")]
        public static IntPtr StartUp(IntPtr userNamePtr, IntPtr passWordPtr){
            client = new SoulseekClient();
            
            string userName = Marshal.PtrToStringAnsi(userNamePtr) ?? "username";
            string passWord = Marshal.PtrToStringAnsi(passWordPtr) ?? "password";
            try
            {
                Connect(userName, passWord);
            }
            catch (System.Exception)
            {
                Console.Write("Exception was caught");
                
            }
            Thread.Sleep(10000);  
            return Marshal.StringToHGlobalAnsi("Connecting to Soulseek");
        }

        private static void Connect(string userName, string passWord) {
            try
            {
                client.ConnectAsync(userName, passWord).RunSynchronously(); 
                
            }
            catch (System.AggregateException)
            {
                Console.WriteLine("System Aggregate Exception");                
            }   
            
        }

        [UnmanagedCallersOnly(EntryPoint = "close")]
        public static void Close(){
            client.Disconnect();
            client.Dispose();
        }


        [UnmanagedCallersOnly(EntryPoint = "write_line")]
        public static int WriteLine(IntPtr pString)
        {
            // The marshalling code is typically auto-generated by a custom tool in larger projects.
            try
            {
                // UnmanagedCallersOnly methods only accept primitive arguments. The primitive arguments
                // have to be marshalled manually if necessary.
                string str = Marshal.PtrToStringAnsi(pString);

                Console.WriteLine(str);
            }
            catch
            {
                // Exceptions escaping out of UnmanagedCallersOnly methods are treated as unhandled exceptions.
                // The errors have to be marshalled manually if necessary.
                return -1;
            }
            return 0;
        }

        [UnmanagedCallersOnly(EntryPoint = "sumstring")]
        public static IntPtr Sumstring(IntPtr first, IntPtr second)
        {
            // Parse strings from the passed pointers 
            string my1String = Marshal.PtrToStringAnsi(first);
            string my2String = Marshal.PtrToStringAnsi(second);

            // Concatenate strings 
            string sum = my1String + my2String;

            // Assign pointer of the concatenated string to sumPointer
            IntPtr sumPointer = Marshal.StringToCoTaskMemAnsi(sum);

            // Return pointer
            return sumPointer;
        }
    }
}